[buildPlans.iosevka-custom]
family = "Iosevka"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.iosevka-custom.variants.design]
capital-q = "crossing"
f = "flat-hook-serifless"
g = "single-storey-earless-corner"
j = "flat-hook-serifed"
k = "straight-serifless"
t = "flat-hook"
u = "tailed-serifless"
lower-lambda = "straight-turn"
two = "straight-neck-serifless"
four = "open-serifless"
paren = "flat-arc"
brace = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-custom.ligations]
inherits = "dlig"
enabled = ["slasheq", "tildeeq"]
disabled = ["bracebar", "brackbar"]
