"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$git_status$fill$all$line_break$character"""

add_newline = false

[time]
disabled = false

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
min_time = 100
show_milliseconds = true

[status]
format = '[\[$int $common_meaning$signal_name\]]($style) '
disabled = false
