"$schema" = 'https://starship.rs/config-schema.json'

format = """$directory$git_branch$git_status$fill$all$line_break$character"""

add_newline = false

[time]
disabled = false

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[cmd_duration]
min_time = 100
show_milliseconds = true

[status]
format = '[\[$int $common_meaning$signal_name\]]($style) '
disabled = false
